### ISSUE TITLE
Failover clustering with external database

### ISSUE THREAD

**Issue by maxinomnom** [zentralopensource/zentral#100]
Hello,

I have Zentral installed on an AWS EC2 instance by the AWS Image and it's working fine. I am only using it as a Santa Server.

I'd like to build a failover solution, so if the server crashes or has to be updated, another one takes over (passive-active-clustering).
For this I need to have all the data (database, configs etc.) on an external instance, so that the failover solution has access to the latest changes and configuration etc....
How could that be possible?
Where are all the Santa Probes, Machine Inventory etc. stored?
Would that be even possible?

**Comment by np5** [comment]
All the probes and the inventory are stored in the PostgreSQL database.

Zentral is a relatively standard web application, with a database, some event processing queues, and some event stores. In the ZAIO instances, all of these components are running in the same VM (and fighting for the CPU/RAM🤞), but you could separate them and have them run in their own VMs. You can also swap some of the components for components managed by the cloud providers (AWS SNS/SQS queues, AWS RDS for PostgreSQL, AWS Elasticsearch domain, GCP cloud pub/sub, GCP cloudSQL, …).

If you decide to swap the database for AWS RDS for PostgreSQL for example, you could get [HA](https://aws.amazon.com/rds/ha/). But you need to think about what other parts of the infrastructure are also going to fail, and how they could recover. And before you get to that, you need also to think about OS security updates, Zentral updates, backups, recovery plans, …

I am going to close this issue, because it is not really related to the code itself. It is more a question about production deployments, and we provide professional services for that. Booking us is one of the best way to support this project.
