### ISSUE TITLE
Enrollment script for Ubuntu fails for Linux Mint 

### ISSUE THREAD

**Issue by JJediny** [zentralopensource/zentral#19]
osquery_zentral_setup.sh

The bash script picks up "rosa" for linux mint 17.3 and "serena" on 18.1 for $DISTRO resulting in a failed execution

**lines 44-47**
```
# add/replace osquery repository
sudo /bin/sed -i '/^deb.*osquery.*$/d' /etc/apt/sources.list
DISTRO=$(lsb_release -c|cut -d ':' -f2| tr  -d "\t")
echo "deb [arch=amd64] https://osquery-packages.s3.amazonaws.com/$DISTRO $DISTRO main" | sudo /usr/bin/tee -a /etc/apt/sources.list
```

**Comment by np5** [comment]
Hi,

Sorry for the late answer.

osquery packages are only available for CentOS/RHEL or Ubuntu > 12.04, AFAIK:

https://osquery.io/downloads/

**Comment by JJediny** [comment]
@np5

linux mint 17 is Ubuntu 14.04
linux mint 18 is Ubuntu 16.04 

the issue here is the bash script is ill-configured and should instead use .deb package check our curl with checksum

**Comment by np5** [comment]
We like to get the updates when they are available, that's why we are using the repository. As a bonus, we don't have to update the script every time there is a new osquery release.

This is not a priority for us to support other distributions.

Just download the script once and change the part where the repository is configured to suit your needs.

**Comment by np5** [comment]
Have you tried the new installer script (see e29ac13) ?

**Comment by np5** [comment]
Closed because no update/answer
