### ISSUE TITLE
Allow whitelist regex for santa monitor mode

### ISSUE THREAD

**Issue by mikemcdonald** [zentralopensource/zentral#54]
Would it be possible to allow a whitelist regex for santa monitor mode? This will allow me to alert on ALLOW_UNKNOWN santa events without lots of false positives of binaries that would be whitelisted by the regex once lockdown mode is eventually turned on

**Comment by np5** [comment]
Thanks for your help! Indeed, events for binaries matched by the `WhitelistRegex` are logged with the `ALLOW_SCOPE` decision, which can be helpful to filter them, even in `MONITOR` mode.

f396b2e fixes this issue.

Note that the `ALLOW_SCOPE` decisions [are not processed as events in santa](https://github.com/google/santa/blob/0c39342d5349fd012e2a8c09c17685d4cbeb2e0a/Source/santad/SNTExecutionController.m#L132). That's why they are not not pushed to Zentral. They are present in the logs, that could be pushed to Zentral, but then we would have to process raw logs with less information, and [we would not get the events anymore](https://github.com/google/santa/blob/0c39342d5349fd012e2a8c09c17685d4cbeb2e0a/Source/santactl/Commands/sync/SNTCommandSyncManager.m#L355).

**Comment by mikemcdonald** [comment]
Wow, this has to be a record for turnaround time on a feature request. Thanks!
