### ISSUE TITLE
AWS all in one

### ISSUE THREAD

**Issue by Ziefin** [zentralopensource/zentral#561]
the aws all in one image is still using the v2021.1 release
also the osquery .sh script is using python2 that's SUPER old and not even relative anymore i'd advise changing that call to python3 at a minimum. This will remove the need to be in a venv to call just base python. No current OS uses python anymore it's python3. 

Also your docker deployment doesn't resolve a hostname to be used for the webserver. it's hardcoded to use just zentral in the zentral.conf file for nginx. I'd advise making this a variable to be used instead of editing the /etc/hosts file. Not a smart move to use dns.

having prebuilt csr, crt and key files is not the way to go. If anything have people provide the dns name and you can use lets encrypt to build the server keys for full dns resolution and there wont be any HSTS errors from the browsers prespective.

**Comment by np5** [comment]
It is true that the AWS test instances are old, but you can update them using the deploy.py script. With the setup.py script in your instance, you were able to pick an FQDN and the certificates were issued using lets encrypt.

We removed the python2 dependence a long time ago. Maybe we have missed something and that would be a bug. Please point to the current code lines if you have find something, and open separate issues.

The docker deployment is for devs. This is why, in order to speed things up, we provide self signed certificates. We also configure everything with "zentral" as (invalid) FQDN so that it doesn't interfere with anything else (HSTS).

For prod deployments using containers, we provide pre-build containers published on the docker registry. There are mechanisms to use environment variables and cloud secrets in base.json that can also really help. We do not provide production ready environments in this repo because they can vary depending on the use of k8s or not, on gcp, aws, azure, … If you want help, contact us directly.

I would also advise you to think about how your comments might be received, and wether they are really helping the project before posting them. We have invested a lot of time building this and giving access to it.
